// apps/react-starter/src/pages/Forms.tsx


import { useState } from 'react';
import {
  IxInput,
  IxSelect,
  IxSelectItem,
  IxDateInput,
  IxRadioGroup,
  IxRadio,
  IxButton,
  IxTypography,
} from '@siemens/ix-react';
import { PAGE_PADDING, FORM_MAX_WIDTH } from '@ix-starter/shared';

function Forms() {
  const [inspectorName, setInspectorName] = useState('');
  const [inspectionType, setInspectionType] = useState('');
  const [inspectionDate, setInspectionDate] = useState('');
  const [inspectionMode, setInspectionMode] = useState('');

  const handleSave = () => {
    console.log({ inspectorName, inspectionType, inspectionDate, inspectionMode });
  };

  const handleCancel = () => {
    setInspectorName('');
    setInspectionType('');
    setInspectionDate('');
    setInspectionMode('');
  };

  return (
    <div style={{ padding: PAGE_PADDING }}>
      <IxTypography format="h1">Forms</IxTypography>
      <IxTypography format="body" style={{ display: 'block', marginTop: '0.5rem', marginBottom: '2rem' }}>
        Siemens Industrial Experience provides consistent form elements for collecting and validating user input.
      </IxTypography>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '1.5rem', maxWidth: FORM_MAX_WIDTH }}>

        <IxInput
          label="Inspector Name"
          placeholder="Jane Doe"
          helperText="Enter the certified inspector's full name"
          value={inspectorName}
          onValueChange={(e) => setInspectorName(e.detail)}
        />

        <IxSelect
          label="Inspection Type"
          helperText="Choose the inspection to perform"
          onValueChange={(e) => setInspectionType(e.detail as string)}
        >
          <IxSelectItem value="visual" label="Visual Inspection" />
          <IxSelectItem value="dimensional" label="Dimensional Check" />
          <IxSelectItem value="functional" label="Functional Test" />
          <IxSelectItem value="pressure" label="Pressure Test" />
        </IxSelect>

        <IxDateInput
          label="Inspection Date"
          helperText="Schedule the inspection"
          onValueChange={(e) => setInspectionDate(e.detail as string)}
        />

        <IxRadioGroup
          label="Inspection Mode"
          helperText="Inline inspections take place during production. Offline sampling requires batch removal for lab testing."
          value={inspectionMode}
          onValueChange={(e) => setInspectionMode(e.detail as string)}
        >
          <IxRadio value="inline" label="In-line inspection" />
          <IxRadio value="offline" label="Offline sampling" />
        </IxRadioGroup>

        <div style={{ display: 'flex', gap: '1rem', marginTop: '0.5rem', justifyContent: 'flex-end' }}>
          <IxButton variant="secondary" onClick={handleCancel}>Cancel</IxButton>
          <IxButton variant="primary" onClick={handleSave}>Save</IxButton>
        </div>

      </div>
    </div>
  );
}

export default Forms;

// apps/angular-starter/src/app/pages/forms/forms.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import {
  IxTypography,
  IxInput,
  IxSelect,
  IxSelectItem,
  IxDateInput,
  IxRadioGroup,
  IxRadio,
  IxButton,
} from '@siemens/ix-angular/standalone';
import { PAGE_PADDING, FORM_MAX_WIDTH } from '@ix-starter/shared';

@Component({
  selector: 'app-forms-page',
  standalone: true,
  imports: [
    FormsModule,
    IxTypography,
    IxInput,
    IxSelect,
    IxSelectItem,
    IxDateInput,
    IxRadioGroup,
    IxRadio,
    IxButton,
  ],
  template: `
    <div class="forms-page" [style.padding]="PAGE_PADDING">
      <ix-typography format="h1">Forms</ix-typography>
      <ix-typography format="body" class="description">
        Siemens Industrial Experience provides consistent form elements for collecting and validating user input.
      </ix-typography>

      <div class="form-container" [style.max-width]="FORM_MAX_WIDTH">
        <ix-input
          label="Inspector Name"
          placeholder="Jane Doe"
          helperText="Enter the certified inspector's full name"
          [value]="inspectorName"
          (valueChange)="inspectorName = $event.detail"
        ></ix-input>

        <ix-select
          label="Inspection Type"
          helperText="Choose the inspection to perform"
          (valueChange)="onInspectionTypeChange($event)"
        >
          <ix-select-item value="visual" label="Visual Inspection"></ix-select-item>
          <ix-select-item value="dimensional" label="Dimensional Check"></ix-select-item>
          <ix-select-item value="functional" label="Functional Test"></ix-select-item>
          <ix-select-item value="pressure" label="Pressure Test"></ix-select-item>
        </ix-select>

        <ix-date-input
          label="Inspection Date"
          helperText="Schedule the inspection"
          (valueChange)="onInspectionDateChange($event)"
        ></ix-date-input>

        <ix-radio-group
          label="Inspection Mode"
          helperText="Inline inspections take place during production. Offline sampling requires batch removal for lab testing."
          [value]="inspectionMode"
          (valueChange)="inspectionMode = $event.detail"
        >
          <ix-radio value="inline" label="In-line inspection"></ix-radio>
          <ix-radio value="offline" label="Offline sampling"></ix-radio>
        </ix-radio-group>

        <div class="button-row">
          <ix-button variant="secondary" (click)="handleCancel()">Cancel</ix-button>
          <ix-button variant="primary" (click)="handleSave()">Save</ix-button>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .description {
      display: block;
      margin-top: 0.5rem;
      margin-bottom: 2rem;
    }
    .form-container {
      display: flex;
      flex-direction: column;
      gap: 1.5rem;
    }
    .button-row {
      display: flex;
      gap: 1rem;
      margin-top: 0.5rem;
      justify-content: flex-end;
    }
  `],
})
export class FormsComponent {
  PAGE_PADDING = PAGE_PADDING;
  FORM_MAX_WIDTH = FORM_MAX_WIDTH;
  inspectorName = '';
  inspectionType = '';
  inspectionDate = '';
  inspectionMode = '';

  onInspectionTypeChange(event: CustomEvent<string | string[]>) {
    const value = event.detail;
    this.inspectionType = Array.isArray(value) ? value[0] || '' : value;
  }

  onInspectionDateChange(event: CustomEvent<string | undefined>) {
    this.inspectionDate = event.detail || '';
  }

  handleSave() {
    console.log({
      inspectorName: this.inspectorName,
      inspectionType: this.inspectionType,
      inspectionDate: this.inspectionDate,
      inspectionMode: this.inspectionMode,
    });
  }

  handleCancel() {
    this.inspectorName = '';
    this.inspectionType = '';
    this.inspectionDate = '';
    this.inspectionMode = '';
  }
}
