// react-starter/src/pages/Forms.tsx
import { useState } from 'react';
import { showMessage } from '@siemens/ix';
import {
  IxInput,
  IxSelect,
  IxSelectItem,
  IxDateInput,
  IxRadioGroup,
  IxRadio,
  IxButton,
  IxContentHeader,
  IxTypography,
} from '@siemens/ix-react';
import {
  FORM_MAX_WIDTH,
  SECTION_MARGIN_TOP,
  SECTION_MARGIN_BOTTOM,
  LABEL_INSPECTOR_NAME,
  LABEL_INSPECTION_TYPE,
  LABEL_INSPECTION_DATE,
  INSPECTION_TYPES,
  PAGE_FORMS,
} from '../shared';

function Forms() {
  const [inspectorName, setInspectorName] = useState('');
  const [inspectionType, setInspectionType] = useState('');
  const [inspectionDate, setInspectionDate] = useState('');
  const [inspectionMode, setInspectionMode] = useState('inline');

  const handleSave = () => {
    console.log({ inspectorName, inspectionType, inspectionDate, inspectionMode });
    showMessage({
      icon: 'info',
      messageTitle: 'Time slot unavailable',
      message: 'Inspections can only be scheduled during operational hours, 06:00–22:00. Select a time within this range.',
      actions: [
        { id: 'cancel', type: 'cancel', text: 'Cancel' },
        { id: 'ok', type: 'okay', text: 'OK' },
      ],
      centered: true,
    });
  };

  const handleCancel = () => {
    setInspectorName('');
    setInspectionType('');
    setInspectionDate('');
    setInspectionMode('');
  };

  return (
    <>
      <IxContentHeader headerTitle={PAGE_FORMS} />
      <IxTypography
        format="body"
        style={{
          display: 'block',
          marginTop: SECTION_MARGIN_TOP,
          marginBottom: SECTION_MARGIN_BOTTOM,
        }}
      >
        Siemens Industrial Experience provides consistent form elements for collecting and
        validating user input.
      </IxTypography>

      <div className="form-container" style={{ maxWidth: FORM_MAX_WIDTH }}>
        <IxInput
          label={LABEL_INSPECTOR_NAME}
          placeholder="Jane Doe"
          helperText="Enter the certified inspector's full name"
          value={inspectorName}
          onValueChange={(e) => setInspectorName(e.detail)}
        />

        <IxSelect
          label={LABEL_INSPECTION_TYPE}
          helperText="Choose the inspection to perform"
          onValueChange={(e) => setInspectionType(e.detail as string)}
        >
          {INSPECTION_TYPES.map((type) => (
            <IxSelectItem key={type} value={type} label={type} />
          ))}
        </IxSelect>

        <IxDateInput
          label={LABEL_INSPECTION_DATE}
          helperText="Schedule the inspection"
          placeholder="DD/MM/YYYY"
          onValueChange={(e) => setInspectionDate(e.detail as string)}
        />

        <IxRadioGroup
          label="Inspection Mode"
          helperText="In-line inspection takes place during production. Offline sampling requires batch removal for lab testing."
          value={inspectionMode}
          onValueChange={(e) => setInspectionMode(e.detail as string)}
        >
          <IxRadio value="inline" label="In-line inspection" />
          <IxRadio value="offline" label="Offline sampling" />
        </IxRadioGroup>

        <div
          style={{
            display: 'flex',
            columnGap: '1rem',
            marginTop: '0.5rem',
            justifyContent: 'flex-end',
          }}
        >
          <IxButton variant="secondary" onClick={handleCancel}>
            {'Cancel'}
          </IxButton>
          <IxButton variant="primary" onClick={handleSave}>
            {'Save'}
          </IxButton>
        </div>
      </div>
    </>
  );
}

export default Forms;

// angular-starter/src/app/pages/forms/forms.component.ts
import { Component } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { showMessage } from '@siemens/ix';
import {
  IxContentHeader,
  IxTypography,
  IxInput,
  IxSelect,
  IxSelectItem,
  IxDateInput,
  IxRadioGroup,
  IxRadio,
  IxButton,
} from '@siemens/ix-angular/standalone';
import {
  FORM_MAX_WIDTH,
  SECTION_MARGIN_TOP,
  SECTION_MARGIN_BOTTOM,
  LABEL_INSPECTOR_NAME,
  LABEL_INSPECTION_TYPE,
  LABEL_INSPECTION_DATE,
  INSPECTION_TYPES,
  PAGE_FORMS,
} from '../../../shared';

@Component({
  selector: 'app-forms-page',
  standalone: true,
  imports: [
    FormsModule,
    IxContentHeader,
    IxTypography,
    IxInput,
    IxSelect,
    IxSelectItem,
    IxDateInput,
    IxRadioGroup,
    IxRadio,
    IxButton,
  ],
  template: `
    <div class="forms-page">
      <ix-content-header [headerTitle]="PAGE_FORMS"></ix-content-header>
      <ix-typography format="body" class="description">
        Siemens Industrial Experience provides consistent form elements for collecting and
        validating user input.
      </ix-typography>

      <div class="form-container" [style.max-width]="FORM_MAX_WIDTH">
        <ix-input
          [attr.label]="LABEL_INSPECTOR_NAME"
          placeholder="Jane Doe"
          helperText="Enter the certified inspector's full name"
          [value]="inspectorName"
          (valueChange)="inspectorName = $event.detail"
        ></ix-input>

        <ix-select
          [attr.label]="LABEL_INSPECTION_TYPE"
          helperText="Choose the inspection to perform"
          (valueChange)="onInspectionTypeChange($event)"
        >
          @for (type of INSPECTION_TYPES; track type) {
            <ix-select-item [value]="type" [label]="type"></ix-select-item>
          }
        </ix-select>

        <ix-date-input
          [attr.label]="LABEL_INSPECTION_DATE"
          helperText="Schedule the inspection"
          placeholder="DD/MM/YYYY"
          (valueChange)="onInspectionDateChange($event)"
        ></ix-date-input>

        <ix-radio-group
          label="Inspection Mode"
          helperText="In-line inspection takes place during production. Offline sampling requires batch removal for lab testing."
          [value]="inspectionMode"
          (valueChange)="inspectionMode = $event.detail"
        >
          <ix-radio value="inline" label="In-line inspection"></ix-radio>
          <ix-radio value="offline" label="Offline sampling"></ix-radio>
        </ix-radio-group>

        <div class="button-row">
          <ix-button variant="secondary" (click)="handleCancel()">Cancel</ix-button>
          <ix-button variant="primary" (click)="handleSave()">Save</ix-button>
        </div>
      </div>
    </div>
  `,
  styles: [
    `
      .page-title {
        display: block;
        margin-bottom: 1.5rem;
      }
      .description {
        display: block;
        margin-top: 0.5rem;
        margin-bottom: 2rem;
      }
      .form-container {
        display: flex;
        flex-direction: column;
        gap: 1.5rem;
      }
      .button-row {
        display: flex;
        gap: 1rem;
        margin-top: 0.5rem;
        justify-content: flex-end;
      }
    `,
  ],
})
export class FormsComponent {
  FORM_MAX_WIDTH = FORM_MAX_WIDTH;
  PAGE_FORMS = PAGE_FORMS;
  LABEL_INSPECTOR_NAME = LABEL_INSPECTOR_NAME;
  LABEL_INSPECTION_TYPE = LABEL_INSPECTION_TYPE;
  LABEL_INSPECTION_DATE = LABEL_INSPECTION_DATE;
  INSPECTION_TYPES = INSPECTION_TYPES;
  inspectorName = '';
  inspectionType = '';
  inspectionDate = '';
  inspectionMode = 'inline';

  onInspectionTypeChange(event: CustomEvent<string | string[]>) {
    const value = event.detail;
    this.inspectionType = Array.isArray(value) ? value[0] || '' : value;
  }

  onInspectionDateChange(event: CustomEvent<string | undefined>) {
    this.inspectionDate = event.detail || '';
  }

  handleSave() {
    console.log({
      inspectorName: this.inspectorName,
      inspectionType: this.inspectionType,
      inspectionDate: this.inspectionDate,
      inspectionMode: this.inspectionMode,
    });
    showMessage({
      icon: 'info',
      messageTitle: 'Time slot unavailable',
      message: 'Inspections can only be scheduled during operational hours, 06:00–22:00. Select a time within this range.',
      actions: [
        { id: 'cancel', type: 'cancel', text: 'Cancel' },
        { id: 'ok', type: 'okay', text: 'OK' },
      ],
      centered: true,
    });
  }

  handleCancel() {
    this.inspectorName = '';
    this.inspectionType = '';
    this.inspectionDate = '';
    this.inspectionMode = '';
  }
}
