// react-starter/src/pages/Grids.tsx
import { IxTypography, IxContentHeader } from '@siemens/ix-react';
import { AgGridReact } from 'ag-grid-react';
import * as ag from 'ag-grid-community';
import { getIxTheme } from '@siemens/ix-aggrid';
import {
  GRID_ROW_DATA,
  GRID_COL_DEFS,
  URL_AG_GRID,
  PAGE_GRIDS,
  GRID_MAX_WIDTH,
} from '../shared';

const ixTheme = getIxTheme(ag).withParams({
  wrapperBorder: false,
  headerRowBorder: true,
  rowBorder: false,
  borderColor: 'var(--theme-color-std-bdr)',
});

function Grids() {
  return (
    <>
      <IxContentHeader headerTitle={PAGE_GRIDS} />
      <IxTypography
        format="body"
        style={{
          display: 'block',
          marginTop: '1.5rem',
          marginBottom: '1.5rem',
        }}
      >
        Siemens Industrial Experience integrates the data grid library{' '}
        <a
          href={URL_AG_GRID}
          target="_blank"
          rel="noreferrer"
          style={{ color: 'inherit', textDecoration: 'underline' }}
        >
          AG Grid
        </a>
        .<br />
        This lets you use its features while staying consistent with the Siemens Industrial
        Experience design system.
      </IxTypography>

      <div style={{ maxWidth: GRID_MAX_WIDTH }}>
        <AgGridReact
          rowData={GRID_ROW_DATA}
          columnDefs={GRID_COL_DEFS}
          domLayout="autoHeight"
          theme={ixTheme}
        />
      </div>
    </>
  );
}

export default Grids;

// angular-starter/src/app/pages/grids/grids.component.ts
import { Component } from '@angular/core';
import { IxContentHeader, IxTypography } from '@siemens/ix-angular/standalone';
import { AgGridAngular } from 'ag-grid-angular';
import * as ag from 'ag-grid-community';
import { ColDef } from 'ag-grid-community';
import { getIxTheme } from '@siemens/ix-aggrid';
import {
  GRID_ROW_DATA,
  GRID_COL_DEFS,
  URL_AG_GRID,
  PAGE_GRIDS,
  type GridRowData,
  GRID_MAX_WIDTH,
} from '../../../shared';

@Component({
  selector: 'app-grids',
  standalone: true,
  imports: [IxContentHeader, IxTypography, AgGridAngular],
  template: `
    <div class="grids-page">
      <ix-content-header [headerTitle]="PAGE_GRIDS"></ix-content-header>
      <ix-typography format="body" class="description">
        Siemens Industrial Experience integrates the data grid library
        <a [href]="urlAgGrid" target="_blank" rel="noreferrer"> AG Grid </a>.
        <br />
        This lets you use its features while staying consistent with the Siemens Industrial
        Experience design system.
      </ix-typography>

      <div [style.maxWidth]="GRID_MAX_WIDTH">
        <ag-grid-angular
          [rowData]="rowData"
          [columnDefs]="columnDefs"
          domLayout="autoHeight"
          [theme]="ixTheme"
        />
      </div>
    </div>
  `,
  styles: [
    `
      .description {
        display: block;
        margin-top: 1.5rem;
        margin-bottom: 1.5rem;
      }
      .description a {
        color: inherit;
        text-decoration: underline;
      }
    `,
  ],
})
export class GridsComponent {
  protected readonly urlAgGrid = URL_AG_GRID;
  protected readonly PAGE_GRIDS = PAGE_GRIDS;
  protected readonly GRID_MAX_WIDTH = GRID_MAX_WIDTH;
  protected readonly ixTheme = getIxTheme(ag).withParams({
    wrapperBorder: false,
    headerRowBorder: true,
    rowBorder: false,
    borderColor: 'var(--theme-color-std-bdr)',
  });

  rowData = GRID_ROW_DATA;

  columnDefs: ColDef<GridRowData>[] = GRID_COL_DEFS;
}
