// angular-starter/src/app/pages/charts/charts.component.ts
import {
  Component,
  CUSTOM_ELEMENTS_SCHEMA,
  ElementRef,
  ViewChild,
  AfterViewInit,
  OnDestroy,
} from '@angular/core';
import { IxContentHeader, IxTypography } from '@siemens/ix-angular/standalone';
import { themeSwitcher } from '@siemens/ix';
import { convertThemeName } from '@siemens/ix-echarts';
import * as echarts from 'echarts/core';
import {
  buildChartOptions,
  URL_ECHARTS,
  CHART_SECTION_TITLE,
  CHART_MAX_WIDTH,
  CHART_HEIGHT,
  CHART_INIT_DELAY_MS,
  PAGE_CHARTS,
} from '../../../shared';

@Component({
  selector: 'app-charts',
  standalone: true,
  imports: [IxContentHeader, IxTypography],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
  template: `
    <div class="charts-page">
      <ix-content-header [headerTitle]="PAGE_CHARTS"></ix-content-header>
      <ix-typography format="body" class="description">
        Siemens Industrial Experience provides an
        <a [href]="urlEcharts" target="_blank" rel="noreferrer">ECharts</a>
        theme.
        <br />
        This lets you use different chart types in the Siemens Industrial Experience design system.
      </ix-typography>

      <ix-typography format="label-lg" bold class="chart-title">{{ chartSectionTitle }}</ix-typography>

      <div
        #chartContainer
        [style.width]="'100%'"
        [style.max-width]="CHART_MAX_WIDTH"
        [style.height]="CHART_HEIGHT"
      ></div>

    </div>
  `,
  styles: [
    `
      .description {
        display: block;
        margin-top: 1.5rem;
        margin-bottom: 1.5rem;
      }
      .description a {
        color: inherit;
        text-decoration: underline;
      }
      .chart-title {
        margin-bottom: 1rem;
      }
    `,
  ],
})
export class ChartsComponent implements AfterViewInit, OnDestroy {
  @ViewChild('chartContainer') chartContainer!: ElementRef<HTMLDivElement>;
  private chartInstance: echarts.ECharts | null = null;

  protected readonly PAGE_CHARTS = PAGE_CHARTS;
  protected readonly urlEcharts = URL_ECHARTS;
  protected readonly chartSectionTitle = CHART_SECTION_TITLE;
  protected readonly CHART_MAX_WIDTH = CHART_MAX_WIDTH;
  protected readonly CHART_HEIGHT = CHART_HEIGHT;
  private readonly chartInitDelayMs = CHART_INIT_DELAY_MS;

  private themeChangeHandler = () => {
    this.chartInstance?.dispose();
    if (!this.chartContainer?.nativeElement) return;
    this.chartInstance = echarts.init(
      this.chartContainer.nativeElement,
      convertThemeName(themeSwitcher.getCurrentTheme())
    );
    this.chartInstance.setOption(buildChartOptions());
  };

  private resizeHandler = () => {
    this.chartInstance?.resize();
  };

  ngAfterViewInit() {
    setTimeout(() => {
      const theme = convertThemeName(themeSwitcher.getCurrentTheme());
      this.chartInstance = echarts.init(this.chartContainer.nativeElement, theme);
      this.chartInstance.setOption(buildChartOptions());

      themeSwitcher.themeChanged.on(this.themeChangeHandler);
      themeSwitcher.schemaChanged.on(this.themeChangeHandler);
      window.addEventListener('resize', this.resizeHandler);
    }, this.chartInitDelayMs);
  }

  ngOnDestroy() {
    themeSwitcher.themeChanged.off(this.themeChangeHandler);
    themeSwitcher.schemaChanged.off(this.themeChangeHandler);
    window.removeEventListener('resize', this.resizeHandler);
    this.chartInstance?.dispose();
  }
}

// react-starter/src/pages/Charts.tsx
import { useEffect, useRef } from 'react';
import { IxTypography, IxContentHeader } from '@siemens/ix-react';
import { themeSwitcher } from '@siemens/ix';
import { convertThemeName } from '@siemens/ix-echarts';
import * as echarts from 'echarts/core';
import {
  buildChartOptions,
  URL_ECHARTS,
  CHART_MAX_WIDTH,
  CHART_HEIGHT,
  CHART_SECTION_TITLE,
  PAGE_CHARTS,
} from '../shared';

function Charts() {
  const chartRef = useRef<HTMLDivElement>(null);
  const instanceRef = useRef<echarts.ECharts | null>(null);

  useEffect(() => {
    if (!chartRef.current) return;

    // Dispose any existing instance first (handles Strict Mode double-invoke)
    if (instanceRef.current) {
      instanceRef.current.dispose();
      instanceRef.current = null;
    }

    // Also check for orphaned instances on the DOM element
    const existingInstance = echarts.getInstanceByDom(chartRef.current);
    if (existingInstance) {
      existingInstance.dispose();
    }

    const theme = convertThemeName(themeSwitcher.getCurrentTheme());
    instanceRef.current = echarts.init(chartRef.current, theme);
    instanceRef.current.setOption(buildChartOptions());

    const handleThemeChange = () => {
      instanceRef.current?.dispose();
      if (!chartRef.current) return;
      instanceRef.current = echarts.init(chartRef.current, convertThemeName(themeSwitcher.getCurrentTheme()));
      instanceRef.current.setOption(buildChartOptions());
    };

    themeSwitcher.themeChanged.on(handleThemeChange);
    themeSwitcher.schemaChanged.on(handleThemeChange);

    const handleResize = () => instanceRef.current?.resize();
    window.addEventListener('resize', handleResize);

    return () => {
      themeSwitcher.themeChanged.off(handleThemeChange);
      themeSwitcher.schemaChanged.off(handleThemeChange);
      window.removeEventListener('resize', handleResize);
      instanceRef.current?.dispose();
    };
  }, []);

  return (
    <>
      <IxContentHeader headerTitle={PAGE_CHARTS} />
      <IxTypography
        format="body"
        style={{
          display: 'block',
          marginTop: '1.5rem',
          marginBottom: '1.5rem',
        }}
      >
        Siemens Industrial Experience provides an{' '}
        <a
          href={URL_ECHARTS}
          target="_blank"
          rel="noreferrer"
          style={{ color: 'inherit', textDecoration: 'underline' }}
        >
          ECharts
        </a>{' '}
        theme. 
        <br />
        This lets you use different chart types in the Siemens Industrial Experience design
        system.
      </IxTypography>

      <IxTypography format="label-lg"bold style={{ marginBottom: '1rem' }}>
        {CHART_SECTION_TITLE}
      </IxTypography>

      <div
        ref={chartRef}
        style={{ width: '100%', maxWidth: CHART_MAX_WIDTH, height: CHART_HEIGHT }}
      />


    </>
  );
}

export default Charts;
