// apps/vue-starter/src/App.vue
<script setup lang="ts">
import { useRouter, useRoute } from 'vue-router';
import {
  IxApplication,
  IxApplicationHeader,
  IxMenu,
  IxMenuItem,
  IxContent,
} from '@siemens/ix-vue';
import { NAV_ITEMS } from '@ix-starter/shared';
import logo from './assets/logo.png';

const router = useRouter();
const route = useRoute();
</script>

<template>
  <IxApplication>
    <IxApplicationHeader name="Siemens Industrial Experience Starter App">
      <div slot="logo">
        <img :src="logo" alt="Siemens" style="height: 40px" />
      </div>
    </IxApplicationHeader>

    <IxMenu enable-toggle-theme>
      <IxMenuItem
        v-for="item in NAV_ITEMS"
        :key="item.path"
        :icon="item.icon"
        :active="route.path === item.path"
        @click="router.push(item.path)"
      >
        {{ item.label }}
      </IxMenuItem>
    </IxMenu>

    <IxContent>
      <router-view />
    </IxContent>
  </IxApplication>
</template>

// apps/react-starter/src/App.tsx
import { Routes, Route, useNavigate, useLocation } from 'react-router-dom';
import {
  IxApplication,
  IxApplicationHeader,
  IxMenu,
  IxMenuItem,
  IxContent
} from '@siemens/ix-react';
import { NAV_ITEMS } from '@ix-starter/shared';

import GetStarted from './pages/GetStarted';
import Forms from './pages/Forms';
import Charts from './pages/Charts';
import Grids from './pages/Grids';
import logo from './assets/logo.png';
import './App.css';

function App() {
  const navigate = useNavigate();
  const location = useLocation();

  const isActive = (path: string): boolean => location.pathname === path;

  return (
    <IxApplication>
      <IxApplicationHeader name="Siemens Industrial Experience Starter App">
        <div slot="logo">
          <img src={logo} alt="Siemens" style={{ height: '40px' }} />
        </div>
      </IxApplicationHeader>

      <IxMenu enableToggleTheme>
        {NAV_ITEMS.map((item) => (
          <IxMenuItem
            key={item.path}
            icon={item.icon}
            active={isActive(item.path)}
            onClick={() => navigate(item.path)}
          >
            {item.label}
          </IxMenuItem>
        ))}
      </IxMenu>

      <IxContent>
        <Routes>
          <Route path="/" element={<GetStarted />} />
          <Route path="/forms" element={<Forms />} />
          <Route path="/charts" element={<Charts />} />
          <Route path="/grids" element={<Grids />} />
          <Route path="*" element={<GetStarted />} />
        </Routes>
      </IxContent>
    </IxApplication>
  );
}

export default App;
