// apps/react-starter/src/pages/Grids.tsx
import { IxTypography } from "@siemens/ix-react";
import { AgGridReact } from "ag-grid-react";
import { ModuleRegistry, AllCommunityModule } from "ag-grid-community";
import { GRID_ROW_DATA, GRID_COL_DEFS, URL_AG_GRID, PAGE_PADDING } from "@ix-starter/shared";
import "ag-grid-community/styles/ag-grid.css";
import "ag-grid-community/styles/ag-theme-alpine.css";
import "@ix-starter/shared/styles/ag-grid-theme.css";

ModuleRegistry.registerModules([AllCommunityModule]);

function Grids() {
  return (
    <div style={{ padding: PAGE_PADDING }}>
      <IxTypography format="h1">Grids</IxTypography>
      <IxTypography
        format="body"
        style={{ display: "block", marginTop: "0.5rem", marginBottom: "2rem" }}
      >
        Siemens Industrial Experience integrates the data grid library{" "}
        <a
          href={URL_AG_GRID}
          target="_blank"
          rel="noreferrer"
          style={{ textDecoration: "underline" }}
        >
          AG Grid
        </a>
        .<br />
        This lets you use its features while staying consistent with the Siemens
        Industrial Experience design system.
      </IxTypography>

      <div className="ag-theme-alpine ix-ag-grid">
        <AgGridReact
          rowData={GRID_ROW_DATA}
          columnDefs={GRID_COL_DEFS}
          domLayout="autoHeight"
          theme="legacy"
        />
      </div>
    </div>
  );
}

export default Grids;

// apps/angular-starter/src/app/pages/grids/grids.component.ts
import { Component } from '@angular/core';
import { IxTypography } from '@siemens/ix-angular/standalone';
import { AgGridAngular } from 'ag-grid-angular';
import { ColDef, ModuleRegistry, AllCommunityModule } from 'ag-grid-community';
import {
  GRID_ROW_DATA,
  GRID_COL_DEFS,
  URL_AG_GRID,
  type GridRowData,
} from '@ix-starter/shared';

ModuleRegistry.registerModules([AllCommunityModule]);

@Component({
  selector: 'app-grids',
  standalone: true,
  imports: [IxTypography, AgGridAngular],
  template: `
    <div class="grids-page">
      <ix-typography format="h1">Grids</ix-typography>
      <ix-typography format="body" class="description">
        Siemens Industrial Experience integrates the data grid library
        <a [href]="urlAgGrid" target="_blank" rel="noreferrer">
          AG Grid
        </a>.
        <br />
        This lets you use its features while staying consistent with the Siemens Industrial Experience design system.
      </ix-typography>

      <div class="ag-theme-alpine ix-ag-grid">
        <ag-grid-angular
          style="width: 100%;"
          [rowData]="rowData"
          [columnDefs]="columnDefs"
          domLayout="autoHeight"
          theme="legacy"
        />
      </div>
    </div>
  `,
  styles: [`
    .grids-page {
      padding: 2rem;
    }
    .description {
      display: block;
      margin-top: 0.5rem;
      margin-bottom: 2rem;
    }
    .description a {
      text-decoration: underline;
    }
  `],
})
export class GridsComponent {
  protected readonly urlAgGrid = URL_AG_GRID;

  rowData = GRID_ROW_DATA;

  columnDefs: ColDef<GridRowData>[] = GRID_COL_DEFS;
}
