// apps/vue-starter/src/App.vue
<template>
  <ix-application>
    <ix-application-header name="Siemens Industrial Experience Starter App">
      <div slot="logo">
        <img :src="logo" alt="Siemens" style="height: 40px" />
      </div>
    </ix-application-header>

    <ix-menu enable-toggle-theme>
      <ix-menu-item
        icon="home"
        :active="route.path === '/'"
        @click="router.push('/')"
      >
        Get Started
      </ix-menu-item>
      <ix-menu-item
        icon="document"
        :active="route.path === '/forms'"
        @click="router.push('/forms')"
      >
        Forms
      </ix-menu-item>
      <ix-menu-item
        icon="barchart"
        :active="route.path === '/charts'"
        @click="router.push('/charts')"
      >
        Charts
      </ix-menu-item>
      <ix-menu-item
        icon="table"
        :active="route.path === '/grids'"
        @click="router.push('/grids')"
      >
        Grids
      </ix-menu-item>
    </ix-menu>

    <ix-content>
      <router-view />
    </ix-content>
  </ix-application>
</template>

<script setup lang="ts">
import { useRouter, useRoute } from 'vue-router';
import logo from './assets/logo.png';

const router = useRouter();
const route = useRoute();
</script>

<style>
html, body, #app {
  height: 100%;
  margin: 0;
  padding: 0;
}
</style>

// src/App.tsx
import { Routes, Route, useNavigate, useLocation } from 'react-router-dom';
import {
  IxApplication,
  IxApplicationHeader,
  IxMenu,
  IxMenuItem,
  IxContent
} from '@siemens/ix-react';

import GetStarted from './pages/GetStarted';
import Forms from './pages/Forms';
import Charts from './pages/Charts';
import Grids from './pages/Grids';
import logo from './utils/logo.png';
import './App.css';

function App() {
  const navigate = useNavigate();
  const location = useLocation();

  const isActive = (path: string): boolean => location.pathname === path;

  return (
    <IxApplication>
      <IxApplicationHeader name="Siemens Industrial Experience Starter App">
        <div slot="logo">
          <img src={logo} alt="Siemens" style={{ height: '40px', mixBlendMode: 'multiply' }} />
        </div>
      </IxApplicationHeader>

      <IxMenu enableToggleTheme>
        <IxMenuItem 
          icon="home" 
          active={isActive('/')}
          onClick={() => navigate('/')}
        >
          Get Started
        </IxMenuItem>
        <IxMenuItem 
          icon="document" 
          active={isActive('/forms')}
          onClick={() => navigate('/forms')}
        >
          Forms
        </IxMenuItem>
        <IxMenuItem 
          icon="barchart" 
          active={isActive('/charts')}
          onClick={() => navigate('/charts')}
        >
          Charts
        </IxMenuItem>
        <IxMenuItem 
          icon="table" 
          active={isActive('/grids')}
          onClick={() => navigate('/grids')}
        >
          Grids
        </IxMenuItem>
      </IxMenu>

      <IxContent>
        <Routes>
          <Route path="/" element={<GetStarted />} />
          <Route path="/forms" element={<Forms />} />
          <Route path="/charts" element={<Charts />} />
          <Route path="/grids" element={<Grids />} />
          <Route path="*" element={<GetStarted />} />
        </Routes>
      </IxContent>
    </IxApplication>
  );
}

export default App;
